language:
- objective-c
env:
  global:
  - BUILD_COMMIT=latest-tag
  - REPO_DIR=scikit-image
  matrix:
  - VERSION=2.7.10 NUMPY_VERSION=1.6.1
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.3 NUMPY_VERSION=1.7.1
  - VERSION=3.5.0 NUMPY_VERSION=1.7.1
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
# Update to latest wheel package for Python 3.5
- pip install -U wheel
- pip install -f $NIPY_WHEELHOUSE numpy==$NUMPY_VERSION cython wheel six matplotlib networkx scipy pillow
- if [ -n "$BUILD_COMMIT" ]; then
      checkout_commit $REPO_DIR $BUILD_COMMIT;
  fi
- cd $REPO_DIR
# Use clang to avoid warnings with Pyton 3.5 headers
- export CC=clang
- export CXX=clang++
- python setup.py bdist_wheel
- delocate-listdeps dist/*.whl # lists library dependencies
- delocate-wheel dist/*.whl # copies library dependencies into wheel
- delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
- pip install dist/*.whl
- cd ..
script:
- pip install nose
# Python 3.4 needs more recent numpy
- if [ -n "$(pyver_ge $VERSION 3.4.0)" ]; then
  pip install --upgrade numpy;
  fi
- mkdir tmp_for_test
- cd tmp_for_test
- nosetests --exe -v skimage
- cd ..
before_deploy: cd $REPO_DIR/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: UUmgPJxMIvdn5ByWI8PQFiT9Nge5/p1iP0ZNfpcG10/aKhYJzh4lwlsLfmTOepm8AwxM5dnJ5kcE5CTzShTBilyygxmo9cRe9ngiFN7SUmBSC+NUxd+OdTbTuCtuv5wwSg4m8ppzmvsp14FdSpb1Ax0A7et0XoRiEV1MlwDFqcQ=
  region: ORD
  container: wheels
  skip_cleanup: true
