language:
- objective-c
env:
  matrix:
  - VERSION=2.7.7 NUMPY_VERSION=1.6.0
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.1 NUMPY_VERSION=1.7.1
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
- pip install -f $NIPY_WHEELHOUSE numpy==$NUMPY_VERSION cython wheel six
- cd scikit-image
- python setup.py bdist_wheel
- rename_wheels dist
- pip install dist/*.whl
- cd ..
script:
- pip install --no-index -f $NIPY_WHEELHOUSE nose scipy pillow matplotlib
  # Segfaults for old numpy and 2.7; syntax errors for numpy and 3.4
- if [ "${VERSION:0:3}" != "3.3" ]; then pip install -U numpy; fi
- mkdir tmp_for_test
- cd tmp_for_test
- nosetests --exe -v skimage
- cd ..
before_deploy: cd scikit-image/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: GfaJ8Y2IYwzkXqHh2rPsDZUJCpMRguJoEdWIIYwH3xyIpt/RiMiicNlMGWLujBZygTKP/3eGcQb8ZNpmkbtaICEMa+3TkySk9mzPwqkYcuyCJAa9Je6vct8Vh53jE6FZ9i0VB7cA0DnTsyFX+4eXHIDl9v4XI1n9MTTfeNT5lVw=
  region: ORD
  container: wheels
  skip_cleanup: true
